"""
Write a python or bash script that counts the number of script files in a directory subdividing it by the shebang interpreter.
"""

import os
import regex as re

# Note: regex should be installed before running the script.
# Random files were generated by randomly selecting the kind of script.


if __name__ == "__main__":
    directory = "../TestFolder"

    # all files in directory
    entries = os.listdir(directory)

    # identify shebang and pick the last piece of the line
    regex = '(?<=#!.*/)[a-zA-Z0-9]+(\s)?(\.|-)?[a-zA-Z0-9]+((?=\n)|$)'

    script_types = {}

    for e in entries:
        f = open(f"{directory}/{e}", "r")
        shebang_line = f.readline()     # read 1 line
        match = re.search(regex, shebang_line).group()

        # create dict of different kind of scripts and count them
        if match not in script_types:
            script_types[match] = 1
        else:
            script_types[match] += 1

    for key, value in script_types.items():
        print(key, " -> ", value)
